// Student screens

function StudentDashboard() {
  return (
    <div className="cg" style={{height: '100%'}}>
      <div className="app">
        <Sidebar role="student" active="dashboard" />
        <div className="main">
          <Topbar />
          <div className="content">
            <div className="page-head">
              <div>
                <div className="eyebrow">Welcome back</div>
                <h1 className="page-title">Good afternoon, Lena.</h1>
                <p className="lede">You're 3 lessons away from finishing <em>Linear Algebra Foundations</em>. Pick up where you left off.</p>
              </div>
              <div style={{display:'flex', gap: 8}}>
                <button className="btn ghost">{Ic.spark} Ask the tutor</button>
                <button className="btn accent">{Ic.play} Continue learning</button>
              </div>
            </div>

            {/* Resume + stats */}
            <div className="grid" style={{gridTemplateColumns: '1.4fr 1fr', gap: 16}}>
              <div className="card" style={{overflow:'hidden'}}>
                <div style={{display: 'grid', gridTemplateColumns: '180px 1fr', gap: 0}}>
                  <div style={{padding: 16}}>
                    <CourseThumb hue={45} h={150} label="Linear Algebra"/>
                  </div>
                  <div style={{padding: '18px 18px 18px 4px'}}>
                    <div className="row" style={{gap: 8, marginBottom: 8}}>
                      <span className="chip accent"><span className="dot"/>In progress</span>
                      <span className="tag">Module 4 · Lesson 2</span>
                    </div>
                    <div className="serif" style={{fontSize: 22, letterSpacing: '-0.02em', marginBottom: 4}}>Eigenvalues & the characteristic polynomial</div>
                    <div className="card-sub" style={{marginBottom: 14}}>Estimated 18 min read · Quiz available after lesson</div>
                    <div style={{display:'flex', alignItems:'center', gap: 14, marginBottom: 14}}>
                      <div style={{flex: 1}}>
                        <div className="row" style={{justifyContent:'space-between', marginBottom: 6}}>
                          <span className="card-sub">Course progress</span>
                          <span className="tag">72%</span>
                        </div>
                        <div className="progress"><i style={{width:'72%'}}/></div>
                      </div>
                    </div>
                    <div style={{display:'flex', gap: 8}}>
                      <button className="btn">Resume lesson {Ic.arrowR}</button>
                      <button className="btn ghost">View syllabus</button>
                    </div>
                  </div>
                </div>
              </div>
              <div className="grid" style={{gridTemplateColumns:'1fr 1fr', gap: 12}}>
                <Stat num="12" label="Day streak" delta="↑ longest yet" />
                <Stat num="87%" label="Avg. quiz score" delta="+4 last 5" />
                <Stat num="4" label="Active courses" sub="2 due this week" />
                <Stat num="38h" label="Time learning" sub="this term" />
              </div>
            </div>

            {/* Today plan + weak topics */}
            <div className="grid" style={{gridTemplateColumns: '1.4fr 1fr', gap: 16, marginTop: 16}}>
              <div className="card">
                <div className="card-head">
                  <div>
                    <div className="card-title">Your plan for today</div>
                    <div className="card-sub">Adaptive — adjusts to your pace and weak areas</div>
                  </div>
                  <span className="chip"><span className="dot" style={{background:'var(--accent)'}}/> Generated by AI</span>
                </div>
                <div>
                  {[
                    { type: "Lesson", title: "Eigenvalues & the characteristic polynomial", course: "Linear Algebra", time: "18 min", state: "active" },
                    { type: "Quiz", title: "Module 4 checkpoint · 8 questions", course: "Linear Algebra", time: "12 min", state: "queued" },
                    { type: "Review", title: "Revisit: dot products (weak topic)", course: "Linear Algebra", time: "6 min", state: "queued" },
                    { type: "Lesson", title: "Sampling distributions intro", course: "Statistics 201", time: "22 min", state: "queued" },
                  ].map((r, i) => (
                    <div key={i} style={{display:'grid', gridTemplateColumns: '60px 1fr auto auto', alignItems:'center', gap: 14, padding: '14px 18px', borderTop: i ? '1px solid var(--hair)' : 'none'}}>
                      <div style={{width: 36, height: 36, borderRadius: 8, background: r.state==='active' ? 'var(--accent)' : 'var(--surface-2)', color: r.state==='active' ? '#fff' : 'var(--ink-2)', display:'grid', placeItems:'center'}}>
                        {r.type === 'Lesson' ? Ic.book : r.type === 'Quiz' ? Ic.mortar : Ic.target}
                      </div>
                      <div>
                        <div style={{fontWeight: 500, fontSize: 13.5}}>{r.title}</div>
                        <div className="card-sub">{r.course} · {r.type}</div>
                      </div>
                      <span className="tag">{r.time}</span>
                      {r.state === 'active'
                        ? <button className="btn sm">Start {Ic.arrowR}</button>
                        : <button className="btn sm ghost">Open</button>}
                    </div>
                  ))}
                </div>
              </div>

              <div className="grid" style={{gap: 16}}>
                <div className="card card-pad">
                  <div className="row" style={{justifyContent:'space-between', marginBottom: 12}}>
                    <div className="card-title">Weak topics</div>
                    <span className="card-sub">last 30 days</span>
                  </div>
                  {[
                    { t: "Eigenvectors", c: "Linear Algebra", v: 42 },
                    { t: "Bayes' theorem", c: "Statistics 201", v: 55 },
                    { t: "Async iterators", c: "Modern JavaScript", v: 61 },
                  ].map((w, i) => (
                    <div key={i} style={{padding: '10px 0', borderBottom: i < 2 ? '1px solid var(--hair)' : 'none'}}>
                      <div className="row" style={{justifyContent:'space-between', marginBottom: 6}}>
                        <div>
                          <div style={{fontSize: 13, fontWeight: 500}}>{w.t}</div>
                          <div className="card-sub">{w.c}</div>
                        </div>
                        <span className="tag">{w.v}% mastery</span>
                      </div>
                      <div className="progress"><i style={{width: w.v + '%', background: w.v < 50 ? 'var(--bad)' : w.v < 70 ? 'var(--warn)' : 'var(--ok)'}}/></div>
                    </div>
                  ))}
                  <button className="btn ghost sm" style={{marginTop: 12, width:'100%', justifyContent:'center'}}>View full progress report</button>
                </div>

                <div className="card warm card-pad">
                  <div className="row" style={{gap: 10, marginBottom: 8}}>
                    <span style={{color:'var(--accent-deep)'}}>{Ic.spark}</span>
                    <div className="card-title" style={{color:'var(--accent-deep)'}}>AI tutor suggestion</div>
                  </div>
                  <div className="serif" style={{fontSize: 17, letterSpacing:'-0.015em', marginBottom: 10}}>
                    "Want a 5-minute refresher on dot products before the next quiz? It'll lift your eigenvectors mastery."
                  </div>
                  <div style={{display:'flex', gap: 8}}>
                    <button className="btn accent sm">Start refresher</button>
                    <button className="btn ghost sm">Not now</button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function CourseCatalog() {
  const courses = [
    { hue: 30, cat: "Mathematics", title: "Linear Algebra Foundations", teacher: "Dr. M. Vance", level: "Intermediate", weeks: 8, rating: 4.8, students: "12.4k", enrolled: true },
    { hue: 65, cat: "Statistics", title: "Statistics 201 · Inference", teacher: "Prof. R. Patel", level: "Intermediate", weeks: 6, rating: 4.7, students: "8.1k", enrolled: true },
    { hue: 130, cat: "Computer Science", title: "Modern JavaScript & the DOM", teacher: "S. Okonkwo", level: "Beginner", weeks: 5, rating: 4.9, students: "21k", enrolled: false },
    { hue: 200, cat: "Computer Science", title: "Data Structures in Practice", teacher: "L. Yamada", level: "Advanced", weeks: 10, rating: 4.6, students: "5.8k", enrolled: false },
    { hue: 260, cat: "Design", title: "Human-Centered Research", teacher: "K. Adebayo", level: "Beginner", weeks: 4, rating: 4.9, students: "3.2k", enrolled: false },
    { hue: 350, cat: "Philosophy", title: "Logic & Argumentation", teacher: "Dr. E. Bauer", level: "Intermediate", weeks: 7, rating: 4.5, students: "1.9k", enrolled: false },
  ];
  return (
    <div className="cg" style={{height: '100%'}}>
      <div className="app">
        <Sidebar role="student" active="catalog" />
        <div className="main">
          <Topbar />
          <div className="content">
            <div className="page-head">
              <div>
                <div className="eyebrow">Course catalog</div>
                <h1 className="page-title">Find your next thing to learn.</h1>
                <p className="lede">412 courses across 14 disciplines. All include adaptive quizzes and an AI tutor that knows the material.</p>
              </div>
            </div>

            {/* Filters */}
            <div className="card card-pad" style={{marginBottom: 18, display:'flex', gap: 10, flexWrap:'wrap', alignItems:'center'}}>
              <span className="tag" style={{marginRight: 6}}>Filter</span>
              {["All disciplines","Mathematics","Computer Science","Statistics","Design","Philosophy"].map((f, i) => (
                <span key={f} className={"chip" + (i === 0 ? " accent" : "")} style={{cursor:'default'}}>{f}</span>
              ))}
              <span style={{flex: 1}}/>
              <span className="chip">{Ic.filter} Level · Any</span>
              <span className="chip">Duration · Any</span>
              <span className="chip">Sort · Popular</span>
            </div>

            {/* Featured */}
            <div className="card" style={{marginBottom: 18, overflow:'hidden', display:'grid', gridTemplateColumns:'1.1fr 1fr'}}>
              <div style={{padding: 28}}>
                <span className="chip accent" style={{marginBottom: 12}}>{Ic.spark} Editors' pick</span>
                <div className="serif" style={{fontSize: 30, letterSpacing:'-0.025em', lineHeight: 1.08, marginBottom: 10}}>
                  The complete path from algebra to deep learning math
                </div>
                <p className="lede" style={{maxWidth: 'none', marginBottom: 18}}>A six-course bundle that takes you from manipulating vectors to deriving backpropagation by hand. Curated by Dr. M. Vance.</p>
                <div style={{display:'flex', gap: 14, fontSize: 13, color: 'var(--muted)', marginBottom: 18}}>
                  <span><b style={{color:'var(--ink)'}}>6</b> courses</span>
                  <span><b style={{color:'var(--ink)'}}>~38 hrs</b> total</span>
                  <span><b style={{color:'var(--ink)'}}>4.8★</b> avg rating</span>
                </div>
                <div style={{display:'flex', gap: 8}}>
                  <button className="btn">Start the path {Ic.arrowR}</button>
                  <button className="btn ghost">Preview syllabus</button>
                </div>
              </div>
              <div style={{padding: 20}}>
                <CourseThumb hue={30} h={220} label="Math path"/>
              </div>
            </div>

            {/* Grid */}
            <div className="grid" style={{gridTemplateColumns: 'repeat(3, 1fr)'}}>
              {courses.map((c, i) => (
                <div key={i} className="card" style={{padding: 14}}>
                  <CourseThumb hue={c.hue} h={120} label={c.cat}/>
                  <div style={{padding: '14px 4px 4px'}}>
                    <div className="row" style={{justifyContent:'space-between', marginBottom: 8}}>
                      <span className="tag">{c.cat.toUpperCase()}</span>
                      <span className="tag">★ {c.rating}</span>
                    </div>
                    <div className="serif" style={{fontSize: 18, letterSpacing:'-0.015em', marginBottom: 6, lineHeight: 1.2}}>{c.title}</div>
                    <div className="card-sub" style={{marginBottom: 12}}>{c.teacher} · {c.weeks} weeks · {c.level}</div>
                    <div className="row" style={{justifyContent:'space-between'}}>
                      <span className="tag">{c.students} learners</span>
                      {c.enrolled
                        ? <span className="chip ok"><span className="dot"/>Enrolled</span>
                        : <button className="btn sm">Enroll</button>}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function CourseDetail() {
  const modules = [
    { n: 1, title: "Vectors & spaces", lessons: 6, done: 6, time: "2h 10m" },
    { n: 2, title: "Matrix operations", lessons: 5, done: 5, time: "1h 50m" },
    { n: 3, title: "Linear transformations", lessons: 7, done: 4, time: "2h 30m" },
    { n: 4, title: "Eigenvalues & eigenvectors", lessons: 6, done: 2, time: "2h 15m", current: true },
    { n: 5, title: "Diagonalization", lessons: 5, done: 0, time: "1h 40m" },
    { n: 6, title: "Applications: PCA & data", lessons: 6, done: 0, time: "2h 20m" },
  ];
  return (
    <div className="cg" style={{height: '100%'}}>
      <div className="app">
        <Sidebar role="student" active="my-courses" />
        <div className="main">
          <Topbar />
          <div className="content">
            <div style={{display:'grid', gridTemplateColumns:'1fr 320px', gap: 24}}>
              <div>
                <div className="row" style={{gap: 8, marginBottom: 14}}>
                  <span className="tag">Browse / Mathematics /</span>
                  <span className="tag" style={{color:'var(--ink-2)'}}>Linear Algebra Foundations</span>
                </div>
                <div className="row" style={{gap: 8, marginBottom: 14}}>
                  <span className="chip accent"><span className="dot"/>In progress · 72%</span>
                  <span className="chip">Intermediate</span>
                  <span className="chip">8 weeks</span>
                  <span className="chip">35 lessons · 6 quizzes</span>
                </div>
                <h1 className="page-title" style={{fontSize: 42, marginBottom: 10}}>Linear Algebra Foundations</h1>
                <p className="lede" style={{fontSize: 16}}>A practitioner's tour through vectors, matrices, and the geometric intuition that makes machine learning click. Built around adaptive quizzes that home in on your weak spots.</p>
                <div className="row" style={{gap: 16, marginTop: 16, marginBottom: 24, color: 'var(--muted)', fontSize: 13}}>
                  <span className="row" style={{gap: 8}}>
                    <span className="avatar" style={{width: 22, height: 22, fontSize: 10, background:'#6b8d68'}}>MV</span>
                    Dr. Marcus Vance
                  </span>
                  <span>★ 4.8 · 12,401 learners</span>
                  <span>Updated Mar 2026</span>
                </div>
                <div style={{display:'flex', gap: 8, marginBottom: 28}}>
                  <button className="btn lg accent">{Ic.play} Resume — Module 4, Lesson 2</button>
                  <button className="btn lg ghost">Course summary (AI)</button>
                </div>

                <div className="serif" style={{fontSize: 22, letterSpacing:'-0.02em', marginBottom: 12}}>What you'll learn</div>
                <div className="grid" style={{gridTemplateColumns:'1fr 1fr', gap: 10, marginBottom: 28}}>
                  {[
                    "Reason about vector spaces geometrically and algebraically",
                    "Decompose matrices and recognize what each piece means",
                    "Compute eigenvalues by hand and on a computer",
                    "Apply linear algebra to PCA and real datasets",
                  ].map((t, i) => (
                    <div key={i} className="row" style={{gap: 10, alignItems:'flex-start'}}>
                      <span style={{color:'var(--accent)', marginTop: 2}}>{Ic.check}</span>
                      <span>{t}</span>
                    </div>
                  ))}
                </div>

                <div className="serif" style={{fontSize: 22, letterSpacing:'-0.02em', marginBottom: 12}}>Curriculum</div>
                <div className="card">
                  {modules.map((m, i) => (
                    <div key={i} style={{padding: '14px 18px', borderTop: i ? '1px solid var(--hair)' : 'none', display:'grid', gridTemplateColumns:'40px 1fr 160px auto', alignItems:'center', gap: 14, background: m.current ? 'var(--accent-tint)' : 'transparent'}}>
                      <div style={{fontFamily:'var(--serif)', fontSize: 22, color: m.current ? 'var(--accent-deep)' : 'var(--faint)'}}>0{m.n}</div>
                      <div>
                        <div style={{fontWeight: 500, marginBottom: 4}}>{m.title}</div>
                        <div className="card-sub">{m.lessons} lessons · {m.time} {m.current && '· You are here'}</div>
                      </div>
                      <div>
                        <div className="row" style={{justifyContent:'space-between', marginBottom: 4}}>
                          <span className="card-sub">{m.done}/{m.lessons}</span>
                          <span className="card-sub">{Math.round((m.done/m.lessons)*100)}%</span>
                        </div>
                        <div className="progress"><i style={{width: (m.done/m.lessons*100)+'%'}}/></div>
                      </div>
                      <button className="btn sm ghost">{m.done === m.lessons ? 'Review' : 'Open'}</button>
                    </div>
                  ))}
                </div>
              </div>

              {/* Sidebar */}
              <div className="grid" style={{gap: 16, alignContent:'start', position:'sticky', top: 0}}>
                <CourseThumb hue={45} h={180} label="Linear Algebra"/>
                <div className="card card-pad">
                  <div className="row" style={{gap: 14, marginBottom: 14}}>
                    <ProgressRing value={72} size={68} />
                    <div>
                      <div className="serif" style={{fontSize: 20, letterSpacing:'-0.02em'}}>72% complete</div>
                      <div className="card-sub">25 of 35 lessons · 3 of 6 quizzes</div>
                    </div>
                  </div>
                  <hr className="hair" style={{margin:'12px 0'}}/>
                  <div className="grid" style={{gridTemplateColumns:'1fr 1fr', gap: 12}}>
                    <div><div className="stat-label">Avg quiz</div><div style={{fontWeight: 500, marginTop: 2}}>89%</div></div>
                    <div><div className="stat-label">Time spent</div><div style={{fontWeight: 500, marginTop: 2}}>14h 22m</div></div>
                    <div><div className="stat-label">Pace</div><div style={{fontWeight: 500, marginTop: 2}}>+3 days ahead</div></div>
                    <div><div className="stat-label">Weak topic</div><div style={{fontWeight: 500, marginTop: 2, color:'var(--bad)'}}>Eigenvectors</div></div>
                  </div>
                </div>
                <div className="card card-pad" style={{background:'var(--surface-2)'}}>
                  <div className="card-title" style={{marginBottom: 6}}>Prerequisites</div>
                  <div className="card-sub">High school algebra & a comfort with functions. We refresh trigonometry along the way.</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function LessonViewer() {
  const sidebar = [
    { n: "4.1", t: "Eigenvalue intuition", done: true },
    { n: "4.2", t: "The characteristic polynomial", active: true },
    { n: "4.3", t: "Computing eigenvectors", done: false },
    { n: "4.4", t: "Geometric multiplicity", done: false },
    { n: "4.5", t: "Complex eigenvalues", done: false },
    { n: "4.6", t: "Module quiz", quiz: true },
  ];
  return (
    <div className="cg" style={{height: '100%'}}>
      <div className="app">
        <Sidebar role="student" active="my-courses" />
        <div className="main">
          <Topbar right={
            <>
              <button className="btn ghost sm">{Ic.spark} Summarize</button>
              <button className="btn ghost sm">{Ic.spark} Ask tutor</button>
              <span className="streak-pill">{Ic.flame} 12</span>
            </>
          }/>
          <div style={{display:'grid', gridTemplateColumns:'260px 1fr 320px', flex: 1, overflow:'hidden'}}>
            {/* Lesson nav */}
            <div style={{borderRight: '1px solid var(--hair)', padding: '20px 14px', overflow:'auto', background: 'var(--surface)'}}>
              <div className="tag" style={{marginBottom: 6}}>MODULE 4 OF 6</div>
              <div className="serif" style={{fontSize: 18, letterSpacing:'-0.02em', marginBottom: 14}}>Eigenvalues & eigenvectors</div>
              <div className="progress" style={{marginBottom: 18}}><i style={{width: '33%'}}/></div>
              {sidebar.map((s, i) => (
                <div key={i} style={{
                  display:'flex', gap: 10, alignItems:'center',
                  padding: '8px 10px', borderRadius: 6, marginBottom: 2,
                  background: s.active ? 'var(--accent-tint)' : 'transparent',
                  color: s.active ? 'var(--accent-deep)' : 'var(--ink-2)',
                }}>
                  <span style={{
                    width: 16, height: 16, borderRadius: 999, border: '1px solid var(--hair-2)',
                    background: s.done ? 'var(--ok)' : s.active ? 'var(--accent)' : s.quiz ? 'var(--surface-2)' : 'transparent',
                    display:'grid', placeItems:'center', color: 'white', fontSize: 9
                  }}>{s.done ? '✓' : s.quiz ? '?' : ''}</span>
                  <span className="tag" style={{color:'inherit'}}>{s.n}</span>
                  <span style={{fontSize: 13}}>{s.t}</span>
                </div>
              ))}
              <hr className="hair" style={{margin: '18px 0'}}/>
              <div className="card warm card-pad" style={{padding: 14}}>
                <div className="card-sub" style={{color:'var(--accent-deep)', marginBottom: 4}}>Next quiz</div>
                <div style={{fontSize: 13, fontWeight: 500, marginBottom: 8}}>Module 4 checkpoint · 8 Qs</div>
                <button className="btn sm accent" style={{width: '100%', justifyContent:'center'}}>Take quiz now</button>
              </div>
            </div>

            {/* Lesson body */}
            <div style={{overflow:'auto', padding: '36px 56px'}}>
              <div className="tag" style={{marginBottom: 10}}>LESSON 4.2 · 18 MIN READ</div>
              <h1 className="serif" style={{fontSize: 40, letterSpacing:'-0.025em', lineHeight: 1.05, margin: '0 0 12px'}}>
                The characteristic polynomial
              </h1>
              <p style={{fontSize: 16, color:'var(--muted)', marginBottom: 28, maxWidth: 620, lineHeight: 1.55}}>
                Every square matrix has a fingerprint — a polynomial whose roots are exactly the eigenvalues. In this lesson we derive it, compute it, and build the intuition you'll need for diagonalization.
              </p>

              <div style={{maxWidth: 680, fontSize: 15.5, lineHeight: 1.7, color: 'var(--ink-2)'}}>
                <p>We start with a deceptively simple question: when does a matrix <span className="mono">A</span> have a non-trivial vector <span className="mono">v</span> that it merely stretches, without rotating? Geometrically, <span className="mono">v</span> survives the transformation along its own line — only its length (and possibly sign) changes.</p>
                <div className="serif" style={{fontSize: 22, marginTop: 28, marginBottom: 10, color:'var(--ink)'}}>From definition to determinant</div>
                <p>If <span className="mono">Av = λv</span>, then <span className="mono">(A − λI)v = 0</span>. For a non-zero <span className="mono">v</span> to satisfy this, the matrix <span className="mono">A − λI</span> must be singular — and that means…</p>

                <div className="card tinted" style={{padding: 18, margin: '20px 0', borderLeft: '3px solid var(--accent)'}}>
                  <div className="tag" style={{color:'var(--accent-deep)', marginBottom: 6}}>KEY RESULT</div>
                  <div style={{fontFamily:'var(--serif)', fontSize: 18, letterSpacing:'-0.01em'}}>
                    The eigenvalues of A are exactly the roots of <span className="mono" style={{background:'var(--bg)', padding:'2px 6px', borderRadius: 4}}>det(A − λI) = 0</span>
                  </div>
                </div>

                <p>This polynomial is called the <em>characteristic polynomial</em> of A. For a 2×2 matrix it's quadratic; for n×n it's degree-n. The Fundamental Theorem of Algebra now tells us there are exactly n eigenvalues, counted with multiplicity — though some may be complex.</p>

                <div className="ph" style={{height: 260, margin: '20px 0'}}>VIDEO · 4-min derivation, 2×2 worked example</div>

                <div className="serif" style={{fontSize: 22, marginTop: 28, marginBottom: 10, color:'var(--ink)'}}>Worked example</div>
                <p>Take <span className="mono">A = [[2, 1], [1, 2]]</span>. Then <span className="mono">A − λI = [[2−λ, 1], [1, 2−λ]]</span> and its determinant is <span className="mono">(2−λ)² − 1 = λ² − 4λ + 3</span>, which factors as…</p>
              </div>

              <div style={{display:'flex', justifyContent:'space-between', marginTop: 36, paddingTop: 24, borderTop: '1px solid var(--hair)'}}>
                <button className="btn ghost">{Ic.arrowL} 4.1 Eigenvalue intuition</button>
                <button className="btn">Mark complete · 4.3 {Ic.arrowR}</button>
              </div>
            </div>

            {/* AI panel */}
            <div style={{borderLeft:'1px solid var(--hair)', padding: 20, background:'var(--surface)', overflow:'auto'}}>
              <div className="row" style={{gap: 8, marginBottom: 14}}>
                <span style={{color:'var(--accent-deep)'}}>{Ic.spark}</span>
                <div className="serif" style={{fontSize: 18, letterSpacing:'-0.02em'}}>Lesson AI</div>
                <span className="chip accent" style={{marginLeft:'auto'}}>Lesson-aware</span>
              </div>

              <div className="card card-pad" style={{marginBottom: 14}}>
                <div className="tag" style={{marginBottom: 8}}>AI SUMMARY · just now</div>
                <div style={{fontSize: 13.5, lineHeight: 1.55}}>
                  Eigenvalues are scalars λ where <span className="mono">Av = λv</span>. They're the roots of <span className="mono">det(A − λI)</span> — the characteristic polynomial. An n×n matrix has n eigenvalues, possibly complex or repeated.
                </div>
                <div style={{display:'flex', gap: 6, marginTop: 12}}>
                  <button className="btn ghost sm">{Ic.copy} Copy</button>
                  <button className="btn ghost sm">Regenerate</button>
                </div>
              </div>

              <div className="tag" style={{marginBottom: 8}}>SUGGESTED QUESTIONS</div>
              {[
                "Why does det(A − λI) = 0 give us eigenvalues?",
                "Can a matrix have complex eigenvalues with real entries?",
                "Walk me through the 2×2 example step by step",
              ].map((q, i) => (
                <div key={i} className="card" style={{padding: '10px 12px', marginBottom: 8, fontSize: 13}}>
                  {q}
                </div>
              ))}

              <hr className="hair" style={{margin:'18px 0'}}/>

              <div className="tag" style={{marginBottom: 8}}>ASK THE TUTOR</div>
              <div className="card" style={{padding: 10, display:'flex', gap: 8, alignItems:'center'}}>
                <input className="in" placeholder="Anything about this lesson…" style={{border:'none', padding: 0}}/>
                <button className="btn sm accent" style={{padding: 6}}>{Ic.send}</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function QuizInProgress() {
  return (
    <div className="cg" style={{height: '100%'}}>
      <div className="app">
        <Sidebar role="student" active="my-courses" />
        <div className="main">
          <div style={{height: 56, borderBottom: '1px solid var(--hair)', background: 'var(--surface)', display:'flex', alignItems:'center', padding:'0 28px', gap: 16}}>
            <div className="row" style={{gap: 10}}>
              <span className="tag">QUIZ · MODULE 4 CHECKPOINT</span>
              <span className="chip accent"><span className="dot"/>Adaptive · current difficulty: medium</span>
            </div>
            <div className="top-actions">
              <span className="chip warn">{Ic.clock} 06:42 remaining</span>
              <button className="btn ghost sm">Save & exit</button>
            </div>
          </div>

          <div style={{padding: '28px 80px', overflow:'auto', flex: 1}}>
            <div style={{maxWidth: 760, margin: '0 auto'}}>
              {/* Progress dots */}
              <div className="row" style={{justifyContent:'space-between', marginBottom: 28}}>
                <div className="row" style={{gap: 4}}>
                  {Array.from({length: 8}).map((_, i) => {
                    const state = i < 3 ? 'done' : i === 3 ? 'active' : 'future';
                    return <div key={i} style={{
                      width: i === 3 ? 32 : 22, height: 6, borderRadius: 999,
                      background: state === 'done' ? 'var(--ok)' : state === 'active' ? 'var(--accent)' : 'var(--surface-3)'
                    }}/>;
                  })}
                </div>
                <span className="tag">Question 4 of 8</span>
              </div>

              <div className="tag" style={{marginBottom: 10}}>EIGENVALUES · DIFFICULTY 0.6 · 1 PT</div>
              <h2 className="serif" style={{fontSize: 30, letterSpacing:'-0.02em', lineHeight: 1.2, fontWeight: 400, margin: '0 0 8px'}}>
                For the matrix <span className="mono" style={{background:'var(--surface-2)', padding:'4px 10px', borderRadius: 6, fontSize: 22}}>A = [[3,1],[0,3]]</span>, which statement is true?
              </h2>
              <p className="card-sub" style={{marginBottom: 28}}>Choose one. You can change your answer until you click Next.</p>

              <div className="grid" style={{gap: 10}}>
                {[
                  { l: "A", t: "A has two distinct real eigenvalues.", sel: false },
                  { l: "B", t: "λ = 3 is a repeated eigenvalue but A has two linearly independent eigenvectors.", sel: false },
                  { l: "C", t: "λ = 3 is a repeated eigenvalue and A has only one linearly independent eigenvector.", sel: true },
                  { l: "D", t: "A has complex eigenvalues.", sel: false },
                ].map((o) => (
                  <div key={o.l} className="card" style={{
                    padding: '14px 18px',
                    display:'grid', gridTemplateColumns:'32px 1fr', gap: 14, alignItems:'center',
                    borderColor: o.sel ? 'var(--accent)' : 'var(--hair)',
                    background: o.sel ? 'var(--accent-tint)' : 'var(--card)',
                    boxShadow: o.sel ? 'inset 0 0 0 1px var(--accent)' : 'none'
                  }}>
                    <div style={{
                      width: 28, height: 28, borderRadius: 999,
                      background: o.sel ? 'var(--accent)' : 'var(--surface-2)',
                      color: o.sel ? '#fff' : 'var(--ink-2)',
                      fontWeight: 500, display:'grid', placeItems:'center'
                    }}>{o.l}</div>
                    <div style={{fontSize: 15}}>{o.t}</div>
                  </div>
                ))}
              </div>

              <div style={{display:'flex', justifyContent:'space-between', marginTop: 36}}>
                <button className="btn ghost">{Ic.arrowL} Previous</button>
                <div style={{display:'flex', gap: 8}}>
                  <button className="btn ghost">Flag for review</button>
                  <button className="btn">Next question {Ic.arrowR}</button>
                </div>
              </div>

              <div className="card warm card-pad" style={{marginTop: 36, display:'grid', gridTemplateColumns:'auto 1fr auto', gap: 14, alignItems:'center'}}>
                <span style={{color:'var(--accent-deep)'}}>{Ic.spark}</span>
                <div>
                  <div style={{fontSize: 13, color:'var(--accent-deep)', fontWeight: 500, marginBottom: 2}}>Stuck on this one?</div>
                  <div className="card-sub">Ask the tutor for a hint — it won't reveal the answer.</div>
                </div>
                <button className="btn sm ghost">Get a hint</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function QuizResults() {
  return (
    <div className="cg" style={{height: '100%'}}>
      <div className="app">
        <Sidebar role="student" active="my-courses" />
        <div className="main">
          <Topbar />
          <div className="content">
            <div className="page-head">
              <div>
                <div className="eyebrow">Module 4 checkpoint · Result</div>
                <h1 className="page-title">You scored 75% — passing.</h1>
                <p className="lede">Adaptive difficulty will rise slightly next time. Two topics to revisit are below.</p>
              </div>
              <div style={{display:'flex', gap: 8}}>
                <button className="btn ghost">Retake quiz</button>
                <button className="btn accent">Continue to 4.3 {Ic.arrowR}</button>
              </div>
            </div>

            <div className="grid" style={{gridTemplateColumns:'1.2fr 1fr', gap: 16}}>
              <div className="card card-pad" style={{display:'grid', gridTemplateColumns:'auto 1fr', gap: 22, alignItems:'center'}}>
                <ProgressRing value={75} size={148} stroke={10} label="75%"/>
                <div>
                  <div className="grid" style={{gridTemplateColumns:'1fr 1fr', gap: 14}}>
                    <div><div className="stat-label">Correct</div><div style={{fontFamily:'var(--serif)', fontSize: 24, letterSpacing:'-0.02em'}}>6 / 8</div></div>
                    <div><div className="stat-label">Time taken</div><div style={{fontFamily:'var(--serif)', fontSize: 24, letterSpacing:'-0.02em'}}>8m 18s</div></div>
                    <div><div className="stat-label">Difficulty</div><div style={{fontFamily:'var(--serif)', fontSize: 24, letterSpacing:'-0.02em'}}>Medium</div></div>
                    <div><div className="stat-label">Next difficulty</div><div style={{fontFamily:'var(--serif)', fontSize: 24, letterSpacing:'-0.02em', color:'var(--accent-deep)'}}>Medium+</div></div>
                  </div>
                  <hr className="hair" style={{margin: '16px 0'}}/>
                  <div className="card-sub">Adaptive engine averaged your last 5 attempts (78, 82, 65, 88, 75 → 76%) and bumped the floor up by one notch.</div>
                </div>
              </div>

              <div className="card card-pad">
                <div className="card-title" style={{marginBottom: 4}}>Topic mastery</div>
                <div className="card-sub" style={{marginBottom: 14}}>How this quiz changed your mastery scores</div>
                {[
                  { t: "Eigenvalue definition", b: 70, a: 85, d: 15 },
                  { t: "Characteristic polynomial", b: 60, a: 72, d: 12 },
                  { t: "Eigenvectors", b: 38, a: 42, d: 4, weak: true },
                  { t: "Algebraic multiplicity", b: 55, a: 50, d: -5, weak: true },
                ].map((m, i) => (
                  <div key={i} style={{padding: '10px 0', borderTop: i ? '1px solid var(--hair)' : 'none'}}>
                    <div className="row" style={{justifyContent:'space-between', marginBottom: 6}}>
                      <div style={{fontSize: 13, fontWeight: 500}}>{m.t}</div>
                      <span className={"tag"} style={{color: m.d > 0 ? 'var(--ok)' : 'var(--bad)'}}>{m.d > 0 ? '+' : ''}{m.d}</span>
                    </div>
                    <div style={{position:'relative', height: 6, background: 'var(--surface-3)', borderRadius: 999}}>
                      <div style={{position:'absolute', left: 0, top: 0, height: '100%', width: m.a+'%', background: m.a < 50 ? 'var(--bad)' : m.a < 70 ? 'var(--warn)' : 'var(--ok)', borderRadius: 999}}/>
                      <div style={{position:'absolute', left: m.b+'%', top: -2, height: 10, width: 2, background:'var(--ink-2)'}}/>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            <div className="card" style={{marginTop: 16}}>
              <div className="card-head">
                <div>
                  <div className="card-title">Question review</div>
                  <div className="card-sub">2 missed. Tap any to see the AI explanation.</div>
                </div>
                <span className="chip">8 questions</span>
              </div>
              {[
                { n: 1, q: "Which is an eigenvector of A = [[2,0],[0,3]]?", ok: true, ans: "[1,0] and [0,1]", you: "Correct" },
                { n: 2, q: "If A is 3×3 with characteristic poly (λ−2)²(λ−5), what is tr(A)?", ok: true, ans: "9", you: "Correct" },
                { n: 3, q: "Eigenvalues of a triangular matrix are…", ok: true, ans: "Diagonal entries", you: "Correct" },
                { n: 4, q: "A = [[3,1],[0,3]] — choose the true statement.", ok: false, ans: "λ=3 repeated, one independent eigenvector", you: "Chose: two independent eigenvectors" },
                { n: 5, q: "Geometric multiplicity is always …", ok: true, ans: "≤ algebraic multiplicity", you: "Correct" },
                { n: 6, q: "det(A − 2I) = 0 means…", ok: false, ans: "2 is an eigenvalue of A", you: "Chose: 2 is a singular value" },
              ].map((r, i) => (
                <div key={i} style={{display:'grid', gridTemplateColumns:'28px 1fr 220px 100px', gap: 14, alignItems:'center', padding: '14px 18px', borderTop: '1px solid var(--hair)'}}>
                  <div style={{
                    width: 22, height: 22, borderRadius: 999, display:'grid', placeItems:'center',
                    background: r.ok ? 'var(--ok-soft)' : 'var(--bad-soft)',
                    color: r.ok ? 'var(--ok)' : 'var(--bad)', fontSize: 12
                  }}>{r.ok ? '✓' : '✗'}</div>
                  <div>
                    <div style={{fontSize: 13.5}}>{r.q}</div>
                    <div className="card-sub">{r.you}</div>
                  </div>
                  <div className="tag" style={{color:'var(--muted)'}}>Answer: {r.ans}</div>
                  <button className="btn sm ghost">Explain</button>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

Object.assign(window, { StudentDashboard, CourseCatalog, CourseDetail, LessonViewer, QuizInProgress, QuizResults });
